name: Firebase Deploy
on:
  push:
    branches:
      - main
jobs:
  build-admin:
    name: Build administrator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm install
      - name: Create .env file
        run: |
          touch .env
          echo VUE_APP_AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }} >> .env
          echo VUE_APP_AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }} >> .env
          echo VUE_APP_AUTH_REDIRECT_URI=https://main.dmrf4lv6h2cuu.amplifyapp.com >> .env
          echo VUE_APP_BACKEND_URL=${{ secrets.VUE_APP_BACKEND_URL }} >> .env
          cat .env
      # - name: Run Tests
      #   env:
      #     CI: true
      #   run: npm run test:unit
      - name: Build
        run: npm run build